schema_version = "1.0.0"


id = "macos"
version = "1.0.0"
name = "MacOS"
tagline = "The MacOS interface style in Blender"
maintainer = "Jay Friesen <jaymfriesen@outlook.com>"

type = "theme"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
   "2024 Jay Friesen",
]
