schema_version = "1.0.0"

id = "limit_texture_size_menu"
version = "1.1.0"
name = "Limit Texture Size Menu"
tagline = "Limit texture sizes in Eevee"
maintainer = "Jay Friesen <jaymfriesen@outlook.com>"
type = "add-on"

website = "https://github.com/stoatsnhoney/limit_texture_size_in_eevee_blender_addon"

tags = ["Render"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
   "2024 Jay Friesen",
]
