schema_version = "1.0.0"

id = "limit_texture_size_menu"
version = "1.0.1"
name = "Limit Texture Size Menu"
tagline = "Adds a menu in the 3D view header to limit texture size"
maintainer = "Jay Friesen <jaymfriesen@outlook.com>"
type = "add-on"

website = "https://github.com/stoatsnhoney/limit-texture-size-menu-blender-addon"

tags = ["Render"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
   "2024 Jay Friesen",
]
